name: quantlab
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.16=py311h50f4ffc_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h982b769_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h237132a_0
  - libcxx=20.1.8=hd7fd590_1
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libffi=3.4.4=hca03da5_1
  - libsodium=1.0.20=h99b78c6_0
  - libzlib=1.3.1=h5f15de7_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h5503f6c_0
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.0.0=py311haa24f5a_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.14=hf701271_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - pyzmq=27.1.0=py311h5a8c52c_1
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=hab6afd1_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.1=py311h80987f9_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiohttp-client-cache==0.11.1
      - aiosignal==1.4.0
      - aiosqlite==0.20.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - brotli==1.2.0
      - cattrs==25.3.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - courlan==1.3.2
      - curl-adapter==1.1.0
      - curl-cffi==0.13.0
      - dateparser==1.2.2
      - deepdiff==8.6.1
      - defusedxml==0.8.0rc2
      - et-xmlfile==2.0.0
      - fastapi==0.120.4
      - frozendict==2.4.7
      - frozenlist==1.8.0
      - h11==0.16.0
      - html5lib==1.1
      - htmldate==1.9.4
      - idna==3.11
      - iniconfig==2.3.0
      - inscriptis==2.7.0
      - itsdangerous==2.2.0
      - justext==3.0.2
      - lxml==5.4.0
      - lxml-html-clean==0.4.3
      - multidict==6.7.0
      - multitasking==0.0.12
      - numpy==2.3.5
      - openbb==4.5.0
      - openbb-benzinga==1.5.0
      - openbb-bls==1.2.0
      - openbb-cftc==1.2.0
      - openbb-commodity==1.4.0
      - openbb-congress-gov==1.1.0
      - openbb-core==1.5.5
      - openbb-crypto==1.5.0
      - openbb-currency==1.5.0
      - openbb-derivatives==1.5.0
      - openbb-econdb==1.4.0
      - openbb-economy==1.5.0
      - openbb-equity==1.5.0
      - openbb-etf==1.5.0
      - openbb-federal-reserve==1.5.0
      - openbb-fixedincome==1.5.0
      - openbb-fmp==1.5.1
      - openbb-fred==1.5.0
      - openbb-imf==1.2.0
      - openbb-index==1.5.0
      - openbb-intrinio==1.5.0
      - openbb-news==1.5.0
      - openbb-oecd==1.5.0
      - openbb-platform-api==1.2.1
      - openbb-polygon==1.5.0
      - openbb-regulators==1.5.0
      - openbb-sec==1.5.0
      - openbb-tiingo==1.5.0
      - openbb-tradingeconomics==1.5.0
      - openbb-us-eia==1.2.0
      - openbb-yfinance==1.5.0
      - openpyxl==3.1.5
      - orderly-set==5.5.0
      - packaging==24.2
      - pandas==2.2.3
      - peewee==3.18.3
      - pluggy==1.6.0
      - propcache==0.4.1
      - protobuf==6.33.1
      - psycopg2-binary==2.9.11
      - pyarrow==22.0.0
      - pycparser==2.23
      - pycurl==7.45.7
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyjwt==2.10.1
      - pytest==9.0.1
      - python-dotenv==1.2.1
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.3
      - quantlab-data-pipeline==0.0.1
      - quantlab-factor-library==0.1.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-cache==1.2.1
      - ruff==0.13.3
      - scipy==1.14.1
      - soupsieve==2.8
      - sqlalchemy==2.0.44
      - starlette==0.49.3
      - tld==0.13.1
      - trafilatura==2.0.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - tzlocal==5.3.1
      - url-normalize==1.4.3
      - urllib3==2.5.0
      - uuid7==0.1.0
      - uvicorn==0.35.0
      - webencodings==0.5.1
      - websockets==15.0.1
      - wrds==3.4.0
      - xlrd==2.0.2
      - xmltodict==0.13.0
      - yarl==1.22.0
      - yfinance==0.2.58
