name: quantlab
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - expat=2.7.3=h982b769_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.11.14=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - beautifulsoup4==4.14.2
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - curl-cffi==0.13.0
      - frozendict==2.4.7
      - idna==3.11
      - iniconfig==2.3.0
      - multitasking==0.0.12
      - numpy==2.3.5
      - packaging==24.2
      - pandas==2.2.3
      - peewee==3.18.3
      - platformdirs==4.5.0
      - pluggy==1.6.0
      - protobuf==6.33.1
      - psycopg2-binary==2.9.11
      - pyarrow==22.0.0
      - pycparser==2.23
      - pygments==2.19.2
      - pytest==9.0.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - six==1.17.0
      - soupsieve==2.8
      - sqlalchemy==2.0.44
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - websockets==15.0.1
      - wrds==3.4.0
      - yfinance==0.2.66
prefix: /Users/edl/miniforge3/envs/quantlab
